server:
  port: 8081

spring:
  application:
    name: fraud
  datasource:
    driver-class-name: org.postgresql.Driver
    password: toor
    url: jdbc:postgresql://localhost:5432/fraud?createDatabaseIfNotExist=true
    username: toor
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: "true" 
      show_sql: true
  zipkin:
    base-url: http://zipkin:9411
eureka:
  client:
    service-url:
      defaultZone: http://eureka_service:8761/eureka
