server:
  port: 8082
spring:
  application:
    name: notification
  datasource:
    password: toor
    url: jdbc:postgresql://localhost:5432/notification?createDatabaseIfNotExist=true
    username: toor
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  zipkin:
    base-url: http://192.168.26.5:9411
    eureka:
      client:
        service-url:
          defaultZone: http://localhost:8761/eureka
        fetch-registry: true
        register-with-eureka: true
        enabled: true