server:
  port: 8080

spring:
  application:
    name: customer
  datasource:
    driver-class-name: org.postgresql.Driver
    password: toor
    url: jdbc:postgresql://localhost:5432/customer?createDatabaseIfNotExist=true
    username: toor

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: "true" # Mettre en citation pour que ce soit interprété comme une chaîne
    show-sql: true # Déplacement de show-sql dans la section properties
