spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  application:
    name: eureka-server
server:
  port: 8761
  zipkin:
    base-url: http://192.168.26.5:9411
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
